version: 2.1

orbs:
  docker: circleci/docker@2.2.0

jobs:
  build-docker-image:
    executor:
      name: docker/docker
      tag: "3.6"
    steps:
      - checkout
      - docker/install-docker-tools
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build Docker Image
          command: |
            export DOCKER_BUILDKIT=0
            echo "Starting building docker image"
            cd XApi
            docker build \
                --build-arg BDD_CONNECTION_STRING="$BDD_CONNECTION_STRING" \
                --build-arg PUBLIC_API_KEY="$PUBLIC_API_KEY" \
                --build-arg PRIVATE_API_KEY="$PRIVATE_API_KEY" \
                -t x-api .
            docker save x-api | gzip > ./x-api.tar.gz
            echo "Docker image built and zipped"
      - persist_to_workspace:
          root: XApi
          paths:
            - x-api.tar.gz
            - docker-compose.yml
            - config/loki-config.yaml
            - config/prometheus.yml
            - config/promtail-config.yaml
  push-docker-image:
    executor:
      name: docker/docker
      tag: "3.6"
    steps:
      - attach_workspace:
          at: XApi
      - run:
          name: Pushing Docker Image
          command: |
            echo "Starting pushing docker image & config to VPS"
            scp -oStrictHostKeyChecking=no XApi/x-api.tar.gz $SSHUSER@$SSHHOST:~/
            scp -oStrictHostKeyChecking=no XApi/docker-compose.yml $SSHUSER@$SSHHOST:~/
            scp -oStrictHostKeyChecking=no XApi/config/* $SSHUSER@$SSHHOST:~/
            echo "Docker image & config pushed to VPS"
            ssh -oStrictHostKeyChecking=no $SSHUSER@$SSHHOST 'gzip -f -d ~/x-api.tar.gz'
            echo "Docker image unzipped"
  serve-docker-image:
    executor:
      name: docker/docker
      tag: "3.6"
    steps:
      - run:
          name: Docker compose down
          command: |
            ssh -oStrictHostKeyChecking=no $SSHUSER@$SSHHOST 'docker compose down'
      - run:
          name: Loading in VPS
          command: |
            ssh -oStrictHostKeyChecking=no $SSHUSER@$SSHHOST 'docker load -i ~/x-api.tar'
      - run:
          name: Docker compose up
          command: |
            ssh -oStrictHostKeyChecking=no $SSHUSER@$SSHHOST 'GF_ADMIN=$GF_ADMIN docker compose up -d'

workflows:
  build-and-deploy:
    jobs:
      - build-docker-image
      - push-docker-image:
          requires:
            - build-docker-image
      - hold:
          type: approval
          requires:
            - push-docker-image
      - serve-docker-image:
          requires:
            - hold
